import Foundation

/// Emits a Swift source file (`GeneratedIndicators.swift`) from an array of `TAFunction` models.
struct SwiftCodeEmitter {
  private let functions: [TAFunction]

  init(functions: [TAFunction]) {
    self.functions = functions
  }

  func emit() -> String {
    var lines: [String] = []
    lines.append("// This file is generated by TACodeGenerator. Do NOT edit manually.")
    lines.append("// Source: Sources/ta-lib/ta_func_api.xml")
    lines.append("")
    lines.append("import ta_lib")
    lines.append("")

    for fn in functions {
      lines.append(contentsOf: emitFunction(fn))
      lines.append("")
    }

    return lines.joined(separator: "\n") + "\n"
  }

  // MARK: - Per-function emission

  private func emitFunction(_ fn: TAFunction) -> [String] {
    var lines: [String] = []

    // Doc comment
    lines.append(contentsOf: emitDocComment(fn))

    // Signature
    let params = buildParams(fn)
    let returnType = buildReturnType(fn)
    let paramStr = params.isEmpty ? "" : "\n        " + params.joined(separator: ",\n        ") + "\n    "
    lines.append("public func \(fn.swiftFuncName)(\(paramStr)) throws(TAError) -> \(returnType) {")

    // Body
    lines.append(contentsOf: emitBody(fn).map { "    " + $0 })

    lines.append("}")
    return lines
  }

  // MARK: - Doc comment

  private func emitDocComment(_ fn: TAFunction) -> [String] {
    var lines: [String] = []

    lines.append("/// \(fn.shortDescription)")
    lines.append("///")
    lines.append("/// **Group:** \(fn.groupId)")

    // - Parameters section
    let priceInputs = fn.requiredInputs.filter { isPriceType($0.type) }
    let arrayInputs = fn.requiredInputs.filter { $0.type == .doubleArray }
    let hasParams = !priceInputs.isEmpty || !arrayInputs.isEmpty || !fn.optionalInputs.isEmpty
    if hasParams {
      lines.append("///")
      lines.append("/// - Parameters:")
      for input in priceInputs {
        let label = priceLabel(input.type)
        lines.append("///   - \(label): \(priceDescription(input.type))")
      }
      if arrayInputs.count == 1 {
        lines.append("///   - \(arrayInputs[0].name): Input values")
      } else {
        for input in arrayInputs {
          lines.append("///   - \(input.name): Input values")
        }
      }
      for opt in fn.optionalInputs {
        var desc = opt.shortDescription.isEmpty ? opt.name : opt.shortDescription
        if let range = opt.range {
          desc += " (\(range.min)...\(range.max))"
        }
        desc += " — default: \(opt.swiftDefault)"
        lines.append("///   - \(opt.swiftLabel): \(desc)")
      }
    }

    // - Returns
    lines.append("///")
    lines.append("/// - Returns: \(returnDescription(fn))")
    lines.append("/// - Throws: ``TAError`` if the computation fails")

    return lines
  }

  private func priceDescription(_ type: InputArgType) -> String {
    switch type {
    case .priceOpen: return "Open price array"
    case .priceHigh: return "High price array"
    case .priceLow: return "Low price array"
    case .priceClose: return "Close price array"
    case .priceVolume: return "Volume array"
    case .priceOpenInterest: return "Open interest array"
    case .doubleArray: return "Input values"
    }
  }

  private func returnDescription(_ fn: TAFunction) -> String {
    if fn.outputs.count == 1 {
      let label = outputLabel(fn.outputs[0].name)
      let type = fn.outputs[0].type == .integerArray ? "IndicatorIntResult" : "IndicatorResult"
      return "``\(type)`` containing `\(label)` values and a `beginIndex` offset"
    }
    let fields = fn.outputs.map { "`\(outputLabel($0.name))`" }.joined(separator: ", ")
    return "Named tuple with \(fields)"
  }

  // MARK: - Parameters

  private func buildParams(_ fn: TAFunction) -> [String] {
    var params: [String] = []

    // Required inputs
    let priceInputs = fn.requiredInputs.filter { isPriceType($0.type) }
    let arrayInputs = fn.requiredInputs.filter { $0.type == .doubleArray }

    if !priceInputs.isEmpty {
      // Labeled price parameters
      for input in priceInputs {
        let label = priceLabel(input.type)
        params.append("\(label): [Double]")
      }
    }

    if arrayInputs.count == 1 {
      // Single Double Array → unlabeled
      params.append("_ \(arrayInputs[0].name): [Double]")
    } else if arrayInputs.count > 1 {
      // Multiple Double Arrays → labeled by XML name
      for input in arrayInputs {
        params.append("\(input.name): [Double]")
      }
    }

    // Optional inputs
    for opt in fn.optionalInputs {
      params.append("\(opt.swiftLabel): \(opt.swiftType) = \(opt.swiftDefault)")
    }

    return params
  }

  // MARK: - Return type

  private func buildReturnType(_ fn: TAFunction) -> String {
    if fn.outputs.count == 1 {
      return fn.outputs[0].type == .integerArray ? "IndicatorIntResult" : "IndicatorResult"
    }
    // Multiple outputs → named tuple
    let fields = fn.outputs.map { out -> String in
      let label = outputLabel(out.name)
      let type = out.type == .integerArray ? "IndicatorIntResult" : "IndicatorResult"
      return "\(label): \(type)"
    }
    return "(" + fields.joined(separator: ", ") + ")"
  }

  // MARK: - Function body

  private func emitBody(_ fn: TAFunction) -> [String] {
    var lines: [String] = []

    // Count expression
    let countExpr = buildCountExpr(fn)
    lines.append("let count = \(countExpr)")
    lines.append("var outBegIdx: Int32 = 0")
    lines.append("var outNBElement: Int32 = 0")

    // Output buffer declarations
    for out in fn.outputs {
      let bufType = out.type == .integerArray ? "Int32" : "Double"
      lines.append("var \(out.swiftName) = [\(bufType)](repeating: 0, count: count)")
    }

    // C function call
    let callArgs = buildCallArgs(fn)
    let cFuncName = "TA_\(fn.abbreviation)"
    lines.append("let retCode = \(cFuncName)(\(callArgs))")

    // Error check
    lines.append("guard retCode == TA_SUCCESS else { throw TAError(retCode: retCode) }")

    // Return statement
    lines.append(contentsOf: buildReturn(fn))

    return lines
  }

  // MARK: - Count expression

  private func buildCountExpr(_ fn: TAFunction) -> String {
    let priceInputs = fn.requiredInputs.filter { isPriceType($0.type) }
    let arrayInputs = fn.requiredInputs.filter { $0.type == .doubleArray }

    var countSources: [String] = []
    for input in priceInputs {
      countSources.append("\(priceLabel(input.type)).count")
    }
    for input in arrayInputs {
      countSources.append(arrayInputs.count == 1 ? "\(input.name).count" : "\(input.name).count")
    }

    if countSources.isEmpty { return "0" }
    if countSources.count == 1 { return countSources[0] }
    return "Swift.min(" + countSources.joined(separator: ", ") + ")"
  }

  // MARK: - C call arguments

  private func buildCallArgs(_ fn: TAFunction) -> String {
    var args: [String] = ["0", "Int32(count - 1)"]

    // Required inputs
    for input in fn.requiredInputs {
      if isPriceType(input.type) {
        args.append(priceLabel(input.type))
      } else {
        args.append(input.name)
      }
    }

    // Optional inputs
    for opt in fn.optionalInputs {
      switch opt.type {
      case .integer:
        args.append(opt.swiftLabel)
      case .double:
        args.append(opt.swiftLabel)
      case .maType:
        args.append("\(opt.swiftLabel).cValue")
      }
    }

    // Output args
    args.append("&outBegIdx")
    args.append("&outNBElement")
    for out in fn.outputs {
      args.append("&\(out.swiftName)")
    }

    return args.joined(separator: ", ")
  }

  // MARK: - Return statement

  private func buildReturn(_ fn: TAFunction) -> [String] {
    let n = fn.outputs.count

    if n == 1 {
      let out = fn.outputs[0]
      let trimmed = "Array(\(out.swiftName).prefix(Int(outNBElement)))"
      let begin = "Int(outBegIdx)"
      if out.type == .integerArray {
        return ["return IndicatorIntResult(values: \(trimmed), beginIndex: \(begin))"]
      } else {
        return ["return IndicatorResult(values: \(trimmed), beginIndex: \(begin))"]
      }
    }

    // Multiple outputs → named tuple
    var lines: [String] = ["return ("]
    for (i, out) in fn.outputs.enumerated() {
      let label = outputLabel(out.name)
      let trimmed = "Array(\(out.swiftName).prefix(Int(outNBElement)))"
      let begin = "Int(outBegIdx)"
      let resultType = out.type == .integerArray ? "IndicatorIntResult" : "IndicatorResult"
      let trailing = i < fn.outputs.count - 1 ? "," : ""
      lines.append("    \(label): \(resultType)(values: \(trimmed), beginIndex: \(begin))\(trailing)")
    }
    lines.append(")")
    return lines
  }

  // MARK: - Helpers

  private func isPriceType(_ type: InputArgType) -> Bool {
    switch type {
    case .priceOpen, .priceHigh, .priceLow, .priceClose, .priceVolume, .priceOpenInterest:
      return true
    case .doubleArray:
      return false
    }
  }

  private func priceLabel(_ type: InputArgType) -> String {
    switch type {
    case .priceOpen: return "open"
    case .priceHigh: return "high"
    case .priceLow: return "low"
    case .priceClose: return "close"
    case .priceVolume: return "volume"
    case .priceOpenInterest: return "openInterest"
    case .doubleArray: return "inReal"
    }
  }

  /// Strips "out" prefix and lowercases first character for tuple labels.
  /// e.g. "outMACD" → "macd", "outAroonDown" → "aroonDown", "outReal" → "real"
  private func outputLabel(_ name: String) -> String {
    let stripped = name.hasPrefix("out") ? String(name.dropFirst(3)) : name
    guard !stripped.isEmpty else { return name }
    return stripped.prefix(1).lowercased() + stripped.dropFirst()
  }
}
